### ISSUE TITLE
decoding a COBSR encoded data block does not result in original data

### ISSUE THREAD

**Issue by kasper64** [cmcqueen/cobs-c#12]
There seems to be an error in the encoder or decoder for C implementation of the COBSR algorithm.
I modified the test code in `tests-c/main.c` to check whether the decoded data resulted in the same as the original data. Sometimes it seems the decoded result is one byte longer. In the other cases the last byte is one higher than the original last byte.
Take the example data: `00 00`, which when encoded and decoded results in `00 00 02`. And `31 32 33 34 35` results in `31 32 33 34 36`

**Comment by cmcqueen** [comment]
It looks as though an error was introduced in the fix for GitHub issue #11.

**Comment by kaspervn** [comment]
Thanks for fixing the issue! I retested and it seems to work now.
